baseurl: https://vvseva.netlify.app/
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: vvseva business card website
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: That is my personal page, that i have for no real reason.
  favicon: sam.ico
  footerText: Vsevolod Suschevskiy (vvsuschevskiy at gmail)
  homepage: main
  images: tn.png
  mainMenu:
    - link: posts
      text: posts
    - link: gallery
      text: gallery
    - link: about
      text: who is Seva
  title: vvseva business card website
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /background.png
        source: /sample_video.mp4
        type: video/mp4
imaging:
  quality: 75
enableEmoji: true
